scrapper/urls.py
from django.urls import path

from . import views

app_name = 'sonic'

urlpatterns = [
    path('', views.index, name='index'),
    path('facebook/', views.facebook, name='facebook'),
    path('twitter/', views.twitter, name='twitter'),
    path('reddit/', views.reddit, name='reddit'),
    path('data/', views.data_analytics, name='data'),
    path('add/', views.add, name='add'),
    path('delete/', views.delete, name='delete'),
    path('lists/', views.lists, name='lists'),
]

social_media_scraper/urls.py
from django.contrib import admin
from django.urls import path,include 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('scrapper/',include("scrapper.urls"))
]

scrapper/models.py
from django.db import models

# Create your models here.
class Message(models.Model):
    username = models.CharField(max_length=50)
    message_time = models.DateField( auto_now=False, auto_now_add=False)
    message = models.CharField(max_length=300)

    def __str__(self):
        return f'{self.username} sent a message that said {self.message} on {self.message_time}'
    

scrapper/forms.py
from django import forms

class TwitterForm(forms.Form):
    phrase = forms.CharField( max_length=100,label="phrase")
    start_date = forms.DateField(required=False)
    end_date = forms.DateField(required=False)

scrapper/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse
from .forms import TwitterForm
from . import models
# Create your views here.
def index(request):
     return render(request, 'scrapper/index.html')

def facebook(request):
     return render(request, 'scrapper/facebook.html')

def twitter(request):
    if request.method =='POST':
        form = TwitterForm(request.POST)
        if form.is_valid():
            print(form.cleaned_data)
            return redirect(reverse('sonic:index'))
    else:
        form = TwitterForm()
    return render(request, 'scrapper/twitter.html',context={'form':form})

def reddit(request):
     return render(request, 'scrapper/reddit.html')

def data_analytics(request):
     return render(request, 'scrapper/data_analysis.html')
    

def add(request):
     if request.POST:
          username = request.POST['username']
          message_time = request.POST['message_time']
          message = request.POST['message']
          models.Message.objects.create(username=username,message_time=message_time,message=message)
          return redirect(reverse('sonic:lists'))
     else:
          return render(request, 'scrapper/add.html')

def delete(request):
     if request.POST:
          pk = request.POST['pk']
          try:
               models.Message.objects.get(pk=pk).delete()
               return redirect(reverse('sonic:lists'))
          except:
               print('pk not found!')
               return redirect(reverse('sonic:lists'))
     return render(request, 'scrapper/delete.html')

def lists(request):
     all_messages = models.Message.objects.all()
     context = {'all_messages':all_messages}
     return render(request, 'scrapper/lists.html', context = context)

scrapper/templates/scrapper/add.html
{% extends 'base.html' %}

{% block content %}
<div class='container'>
    <h1>You made it to add</h1>
    <h2>You changed something</h2>
    <form action = "" method="POST">
        {% csrf_token %}
        <div class="form-group">
            <label for="username">username:</label>
            <input class='form-control' type="text" id='username' name ='username'>
        </div>
        <div class="form-group">
            <label for="message_time">time:</label>
            <input class='form-control'type="text"  id='message_time' name ='message_time'>
        </div>
        <div class="form-group">
            <label for="message">message content:</label>
            <input class='form-control' type="text" id='message' name ='message'>
        </div>
        <input class ='btn btn-primary' type="submit">
    </form>
</div>

{% endblock  %}

scrapper/templates/scrapper/data_analysis.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <body>
        <h1>This is the Data Analytics Site</h1>
        <h3>To return to the mainpage, click below</h3>
        <h1><a href="{% url 'sonic:index' %}">Click here</a></h1>
    </body>
</body>
</html>

scrapper/templates/scrapper/delete.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h1>You made it to Delete</h1>
    <form action="" method='POST'>
        {% csrf_token %}
        <div class="form-group">
            <label for="pk">PK Number</label>
            <input class='form-control' id='pk' name = 'pk' type="text">
        </div>
        <input type="submit" class="'btn btn-primary" >
    </form>
</div>

{% endblock  %}

scrapper/templates/scrapper/facebook.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Facebook</title>
</head>
<body>
    <h1>This is the Facebook Scrapping Site</h1>
    <h3>To return to the mainpage, click below</h3>
    <h1><a href="{% url 'sonic:index' %}">Click here</a></h1>
</body>
</html>

scrapper/templates/scrapper/index.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Scrapper Page</title>
</head>
<body>
    <h1>Welcome to the Scrapper Page</h1>
    <h2>In order to get to other pages, please click the link below</h2>
    <h3>For Facebook, click below</h3>
    <h1><a href="{% url 'sonic:facebook' %}">Click here</a></h1>

    <h3>For Twitter, click below</h3>
    <h1><a href="{% url 'sonic:twitter' %}">Click here</a></h1>

    <h3>For Reddit, click below</h3>
    <h1><a href="{% url 'sonic:reddit' %}">Click here</a></h1>
</body>
</html>

scrapper/templates/scrapper/lists.html
{% extends 'base.html' %}

{% block content %}
<div class = 'container'>
    <h1>List</h1>
    <ul>
        {% for message in all_messages %}
                <li>{{message}}</li>
        {% endfor %}
    </ul>
</div>
{% endblock  %}

scrapper/templates/scrapper/reddit.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Reddit</title>
</head>
<body>
    <h1>This is the Reddit Scrapping Site</h1>
    <form method="post">
        <input type="submit">
    </form>
    <h3>To return to the mainpage, click below</h3>
    <h1><a href="{% url 'sonic:index' %}">Click here</a></h1>
</body>
</html>

scrapper/templates/scrapper/twitter.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Twitter</title>
</head>
<body>
    <h1>This is the Twitter Scrapping Site</h1>
    <form method="post">
        {% csrf_token %}
        {{form}}
        <input type="submit">
    </form>

    <h3>To return to the mainpage, click below</h3>
    <h1><a href="{% url 'sonic:index' %}">Click here</a></h1>
    <h1><a href="{% url 'sonic:data' %}">Click here</a></h1>
</body>
</html>

templates/base.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Landing Page</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'sonic:add' %}">Add</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'sonic:delete' %}">Delete</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'sonic:lists' %}">List</a>
              </li>
          
            </ul>
          </div>
        </div>
      </nav>
    {% block content %}{% endblock  %}
</body>
</html>